name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run-script build-prod
